set.seed(123)
myplot <- xqqmath(~runif(100))
printPlot(myplot,file="nq-unif-departure",size="medium")
myplot <- xqqmath(~rexp(100))
printPlot(myplot,file="nq-exp-departure",size="medium")
myplot <- xqqmath(~rchisq(100,df=2))
printPlot(myplot,file="nq-chisq-departure",size="medium")
dd <- (rcauchy(40))
dd <- c(dd,jitter(-dd))
myplot <- xqqmath(~dd)
printPlot(myplot,file="nq-cauchy-departure",size="medium")
